/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all ingredients
         * @description Retrieve a paginated list of all ingredients with optional filtering
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (1-based) */
                    page?: number;
                    /** @description Number of items per page */
                    limit?: number;
                    /** @description Search term for ingredient name or category */
                    search?: string;
                    /** @description Filter by ingredient status */
                    status?: "Active" | "Inactive" | "Discontinued";
                    /** @description Filter by ingredient category */
                    category?: string;
                    /** @description Filter by ingredient type */
                    type?: "Wet" | "Dry";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetIngredientsResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new ingredient
         * @description Create a new ingredient with full nutritional and supplier information
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateIngredientRequest"];
                };
            };
            responses: {
                /** @description Ingredient created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateIngredientResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Ingredient already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get ingredient by ID
         * @description Retrieve a specific ingredient by its ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Ingredient ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            data: components["schemas"]["Ingredient"];
                        };
                    };
                };
                /** @description Ingredient not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Update ingredient
         * @description Update an existing ingredient
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Ingredient ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateIngredientRequest"];
                };
            };
            responses: {
                /** @description Ingredient updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            data: components["schemas"]["Ingredient"];
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Ingredient not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete ingredient
         * @description Delete an existing ingredient
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Ingredient ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ingredient deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                        };
                    };
                };
                /** @description Ingredient not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all suppliers
         * @description Retrieve a list of all suppliers
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetSuppliersResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Allergens: {
            wheat: boolean;
            fish: boolean;
            crustacean: boolean;
            mollusc: boolean;
            egg: boolean;
            milk: boolean;
            lupin: boolean;
            peanut: boolean;
            soy: boolean;
            sesame: boolean;
            almond: boolean;
            brazilNut: boolean;
            cashew: boolean;
            hazelnut: boolean;
            macadamia: boolean;
            pecan: boolean;
            pistachio: boolean;
            pineNut: boolean;
            walnut: boolean;
            barley: boolean;
            oats: boolean;
            rye: boolean;
            sulphites: boolean;
        };
        /** @enum {string} */
        IngredientCategory: "Mix-in" | "Dried Fruit" | "Other" | "Flavour" | "Fruit" | "Sugar" | "Alcohol" | "Vegetable" | "Seed" | "Dairy" | "Chocolate" | "Oil" | "Stabilizer" | "Grain";
        SugarsPer100g: {
            sucrose: number;
            fructose: number;
            glucose: number;
            dextrose: number;
            alcohol: number;
            other: number;
        };
        SupplierContactInfo: {
            /** Format: email */
            email?: string;
            phone?: string;
            address?: string;
        };
        Supplier: {
            id: string;
            name: string;
            contactInfo: components["schemas"]["SupplierContactInfo"];
            /** Format: uri */
            website?: string;
        };
        Ingredient: {
            id: string;
            name: string;
            supplierID: string;
            /** @enum {string} */
            status: "Active" | "Inactive" | "Discontinued";
            category: components["schemas"]["IngredientCategory"];
            /** @enum {string} */
            type: "Wet" | "Dry";
            brand: string;
            foodCompositionID: string;
            energyPer100g: number;
            proteinPer100g: number;
            totalFatPer100g: number;
            saturatedFatPer100g: number;
            totalCarbPer100g: number;
            totalSugarsPer100g: number;
            sodiumMgPer100g: number;
            waterPer100g: number;
            sugarsPer100g: components["schemas"]["SugarsPer100g"];
            totalSolidsPer100g: number;
            otherSolidsPer100g: number;
            MSNFPer100g: number;
            PAC: number;
            POD: number;
            HF: number;
            dryCocoaSolidsPer100g: number;
            cocoaButterPer100g: number;
            supplier: components["schemas"]["Supplier"];
            supplierCode: string;
            packageSizeInGrams: number;
            costPerPackInCentsExGST: number;
            costPer1000gInCentsExGST: number;
            percentOfUsefulProduct: number;
            allergens: components["schemas"]["Allergens"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastModifiedAt: string;
        };
        CreateIngredientRequest: {
            name: string;
            supplierID: string;
            /** @enum {string} */
            status: "Active" | "Inactive" | "Discontinued";
            category: components["schemas"]["IngredientCategory"];
            /** @enum {string} */
            type: "Wet" | "Dry";
            brand: string;
            foodCompositionID: string;
            energyPer100g: number;
            proteinPer100g: number;
            totalFatPer100g: number;
            saturatedFatPer100g: number;
            totalCarbPer100g: number;
            totalSugarsPer100g: number;
            sodiumMgPer100g: number;
            waterPer100g: number;
            sugarsPer100g: components["schemas"]["SugarsPer100g"];
            totalSolidsPer100g: number;
            otherSolidsPer100g: number;
            MSNFPer100g: number;
            PAC: number;
            POD: number;
            HF: number;
            dryCocoaSolidsPer100g: number;
            cocoaButterPer100g: number;
            supplierCode: string;
            packageSizeInGrams: number;
            costPerPackInCentsExGST: number;
            costPer1000gInCentsExGST: number;
            percentOfUsefulProduct: number;
            allergens: components["schemas"]["Allergens"];
        };
        UpdateIngredientRequest: {
            name?: string;
            supplierID?: string;
            /** @enum {string} */
            status?: "Active" | "Inactive" | "Discontinued";
            category?: components["schemas"]["IngredientCategory"];
            /** @enum {string} */
            type?: "Wet" | "Dry";
            brand?: string;
            foodCompositionID?: string;
            energyPer100g?: number;
            proteinPer100g?: number;
            totalFatPer100g?: number;
            saturatedFatPer100g?: number;
            totalCarbPer100g?: number;
            totalSugarsPer100g?: number;
            sodiumMgPer100g?: number;
            waterPer100g?: number;
            sugarsPer100g?: components["schemas"]["SugarsPer100g"];
            totalSolidsPer100g?: number;
            otherSolidsPer100g?: number;
            MSNFPer100g?: number;
            PAC?: number;
            POD?: number;
            HF?: number;
            dryCocoaSolidsPer100g?: number;
            cocoaButterPer100g?: number;
            supplierCode?: string;
            packageSizeInGrams?: number;
            costPerPackInCentsExGST?: number;
            costPer1000gInCentsExGST?: number;
            percentOfUsefulProduct?: number;
            allergens?: components["schemas"]["Allergens"];
        };
        PaginationMeta: {
            currentPage: number;
            totalPages: number;
            totalCount: number;
            pageSize: number;
        };
        GetIngredientsResponse: {
            success: boolean;
            data: {
                ingredients: components["schemas"]["Ingredient"][];
                pagination: components["schemas"]["PaginationMeta"];
            };
        };
        CreateIngredientResponse: {
            success: boolean;
            data: components["schemas"]["Ingredient"];
        };
        GetSuppliersResponse: {
            success: boolean;
            data: components["schemas"]["Supplier"][];
        };
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

// Convenience type exports for easier usage
export type Ingredient = components['schemas']['Ingredient'];
export type Supplier = components['schemas']['Supplier'];
export type Allergens = components['schemas']['Allergens'];
export type SugarsPer100g = components['schemas']['SugarsPer100g'];
export type SupplierContactInfo = components['schemas']['SupplierContactInfo'];
export type IngredientCategory = components['schemas']['IngredientCategory'];

// Common/shared primitive types (from common.ts)
export type ID = string;
export type ISODateString = string;

// Request/Response types
export type GetIngredientsResponse = components['schemas']['GetIngredientsResponse'];
export type CreateIngredientRequest = components['schemas']['CreateIngredientRequest'];
export type CreateIngredientResponse = components['schemas']['CreateIngredientResponse'];
export type UpdateIngredientRequest = components['schemas']['UpdateIngredientRequest'];
export type GetSuppliersResponse = components['schemas']['GetSuppliersResponse'];
export type ErrorResponse = components['schemas']['ErrorResponse'];
export type PaginationMeta = components['schemas']['PaginationMeta'];

// Common enums
export type IngredientStatus = 'Active' | 'Inactive' | 'Discontinued';
export type IngredientType = 'Wet' | 'Dry';

// Additional response types for specific operations
export type GetIngredientResponse = {
  success: boolean;
  data: Ingredient;
};

export type UpdateIngredientResponse = {
  success: boolean;
  data: Ingredient;
};

export type DeleteIngredientResponse = {
  success: boolean;
  message: string;
};

// Legacy pagination support
export type PaginationResponse = {
  currentPage: number;
  totalPages: number;
  totalCount: number;
  pageSize: number;
};

// Extract operation types for type-safe API calls
export type GetIngredientsParams = paths['/ingredients']['get']['parameters']['query'];
export type GetIngredientByIdParams = paths['/ingredients/{id}']['get']['parameters']['path'];
export type CreateIngredientBody = paths['/ingredients']['post']['requestBody']['content']['application/json'];
export type UpdateIngredientParams = paths['/ingredients/{id}']['put']['parameters']['path'];
export type UpdateIngredientBody = paths['/ingredients/{id}']['put']['requestBody']['content']['application/json'];
export type DeleteIngredientParams = paths['/ingredients/{id}']['delete']['parameters']['path'];
