// Simple static data for seeding - copying the sample ingredients
export const sampleIngredients = [
  {
    id: "ing-1",
    name: "Vanilla Extract",
    supplierID: "sup-1",
    status: "Active" as const,
    category: "Flavour",
    type: "Wet" as const,
    brand: "Pure Vanilla Co.",
    foodCompositionID: "FC-001",
    energyPer100g: 288,
    proteinPer100g: 0.1,
    totalFatPer100g: 0.1,
    saturatedFatPer100g: 0.0,
    totalCarbPer100g: 12.7,
    totalSugarsPer100g: 12.7,
    sodiumMgPer100g: 9,
    waterPer100g: 87.0,
    sugarsPer100g: {
      sucrose: 10.0,
      fructose: 1.5,
      glucose: 1.2,
      dextrose: 0.0,
      alcohol: 0.0,
      other: 0.0,
    },
    totalSolidsPer100g: 13.0,
    otherSolidsPer100g: 0.2,
    MSNFPer100g: 0.1,
    PAC: 0.0,
    POD: 0.0,
    HF: 0.0,
    dryCocoaSolidsPer100g: 0.0,
    cocoaButterPer100g: 0.0,
    supplier: {
      id: "sup-1",
      name: "Pure Vanilla Co.",
      contactInfo: {
        email: "info@purevanilla.com",
        phone: "+1-555-1234",
        address: "123 Flavor St, Vanilla City, VC 12345",
      },
      website: "https://purevanilla.com",
    },
    supplierCode: "VAN-EXT-001",
    packageSizeInGrams: 1000,
    costPerPackInCentsExGST: 2500,
    costPer1000gInCentsExGST: 2500,
    percentOfUsefulProduct: 100,
    allergens: {
      wheat: false,
      fish: false,
      crustacean: false,
      mollusc: false,
      egg: false,
      milk: false,
      lupin: false,
      peanut: false,
      soy: false,
      sesame: false,
      almond: false,
      brazilNut: false,
      cashew: false,
      hazelnut: false,
      macadamia: false,
      pecan: false,
      pistachio: false,
      pineNut: false,
      walnut: false,
      barley: false,
      oats: false,
      rye: false,
      sulphites: false,
    },
    createdAt: "2023-01-01T00:00:00.000Z",
    lastModifiedAt: "2023-01-01T00:00:00.000Z",
  },
  {
    id: "ing-2",
    name: "Milk Chocolate Chips",
    supplierID: "sup-2",
    status: "Active" as const,
    category: "Chocolate",
    type: "Dry" as const,
    brand: "ChocoDelight",
    foodCompositionID: "FC-002",
    energyPer100g: 2230,
    proteinPer100g: 7.7,
    totalFatPer100g: 29.7,
    saturatedFatPer100g: 18.5,
    totalCarbPer100g: 56.4,
    totalSugarsPer100g: 51.5,
    sodiumMgPer100g: 79,
    waterPer100g: 1.5,
    sugarsPer100g: {
      sucrose: 45.0,
      fructose: 0.0,
      glucose: 0.0,
      dextrose: 0.0,
      alcohol: 0.0,
      other: 6.5,
    },
    totalSolidsPer100g: 98.5,
    otherSolidsPer100g: 10.9,
    MSNFPer100g: 7.7,
    PAC: 0.0,
    POD: 0.0,
    HF: 0.0,
    dryCocoaSolidsPer100g: 10.0,
    cocoaButterPer100g: 20.0,
    supplier: {
      id: "sup-2",
      name: "ChocoDelight Inc.",
      contactInfo: {
        email: "sales@chocodelight.com",
        phone: "+1-555-5678",
        address: "456 Cocoa Ave, Chocolate Town, CT 67890",
      },
      website: "https://chocodelight.com",
    },
    supplierCode: "CHOC-CHIP-001",
    packageSizeInGrams: 5000,
    costPerPackInCentsExGST: 15000,
    costPer1000gInCentsExGST: 3000,
    percentOfUsefulProduct: 100,
    allergens: {
      wheat: false,
      fish: false,
      crustacean: false,
      mollusc: false,
      egg: false,
      milk: true,
      lupin: false,
      peanut: false,
      soy: true,
      sesame: false,
      almond: false,
      brazilNut: false,
      cashew: false,
      hazelnut: false,
      macadamia: false,
      pecan: false,
      pistachio: false,
      pineNut: false,
      walnut: false,
      barley: false,
      oats: false,
      rye: false,
      sulphites: false,
    },
    createdAt: "2023-02-01T00:00:00.000Z",
    lastModifiedAt: "2023-02-01T00:00:00.000Z",
  },
  {
    id: "ing-3",
    name: "Strawberry Puree",
    supplierID: "sup-3",
    status: "Active" as const,
    category: "Fruit",
    type: "Wet" as const,
    brand: "BerryFresh",
    foodCompositionID: "FC-003",
    energyPer100g: 32,
    proteinPer100g: 0.7,
    totalFatPer100g: 0.3,
    saturatedFatPer100g: 0.0,
    totalCarbPer100g: 7.7,
    totalSugarsPer100g: 4.7,
    sodiumMgPer100g: 1,
    waterPer100g: 91.0,
    sugarsPer100g: {
      sucrose: 0.5,
      fructose: 2.4,
      glucose: 2.0,
      dextrose: 0.0,
      alcohol: 0.0,
      other: 0.0,
    },
    totalSolidsPer100g: 9.0,
    otherSolidsPer100g: 1.3,
    MSNFPer100g: 0.7,
    PAC: 0.0,
    POD: 0.0,
    HF: 0.0,
    dryCocoaSolidsPer100g: 0.0,
    cocoaButterPer100g: 0.0,
    supplier: {
      id: "sup-3",
      name: "BerryFresh Farms",
      contactInfo: {
        email: "contact@berryfresh.com",
        phone: "+1-555-9012",
        address: "789 Fruit Lane, Berry Valley, BV 34567",
      },
      website: "https://berryfresh.com",
    },
    supplierCode: "STR-PUR-001",
    packageSizeInGrams: 2000,
    costPerPackInCentsExGST: 8000,
    costPer1000gInCentsExGST: 4000,
    percentOfUsefulProduct: 100,
    allergens: {
      wheat: false,
      fish: false,
      crustacean: false,
      mollusc: false,
      egg: false,
      milk: false,
      lupin: false,
      peanut: false,
      soy: false,
      sesame: false,
      almond: false,
      brazilNut: false,
      cashew: false,
      hazelnut: false,
      macadamia: false,
      pecan: false,
      pistachio: false,
      pineNut: false,
      walnut: false,
      barley: false,
      oats: false,
      rye: false,
      sulphites: false,
    },
    createdAt: "2023-03-01T00:00:00.000Z",
    lastModifiedAt: "2023-03-01T00:00:00.000Z",
  }
];
